package com.hologrampacific.flyergoblin.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

class GreenMintTheme(val mode: AppColorTheme.LightMode, val contrast: AppColorTheme.Contrast) :
  AppColorTheme {

  override val colorScheme: ColorScheme
    get() {
      return materialColorTheme.colorScheme(mode, contrast)
    }

  override val goblinColor
    get() = colorScheme.primary

  private val materialColorTheme = InternalMaterialColorTheme()

  private class InternalMaterialColorTheme : MaterialColorTheme {
    override val primaryLight = Color(0xFF264500)
    override val onPrimaryLight = Color(0xFFFFFFFF)
    override val primaryContainerLight = Color(0xFF365F00)
    override val onPrimaryContainerLight = Color(0xFFA7D871)
    override val secondaryLight = Color(0xFF51643C)
    override val onSecondaryLight = Color(0xFFFFFFFF)
    override val secondaryContainerLight = Color(0xFFD1E7B5)
    override val onSecondaryContainerLight = Color(0xFF556940)
    override val tertiaryLight = Color(0xFF004638)
    override val onTertiaryLight = Color(0xFFFFFFFF)
    override val tertiaryContainerLight = Color(0xFF00604D)
    override val onTertiaryContainerLight = Color(0xFF8BD8C0)
    override val errorLight = Color(0xFFB41C1B)
    override val onErrorLight = Color(0xFFFFFFFF)
    override val errorContainerLight = Color(0xFFD83831)
    override val onErrorContainerLight = Color(0xFFFFFBFF)
    override val backgroundLight = Color(0xFFF9FAEE)
    override val onBackgroundLight = Color(0xFF1A1D15)
    override val surfaceLight = Color(0xFFF9FAEE)
    override val onSurfaceLight = Color(0xFF1A1D15)
    override val surfaceVariantLight = Color(0xFFDFE5D1)
    override val onSurfaceVariantLight = Color(0xFF43493A)
    override val outlineLight = Color(0xFF737969)
    override val outlineVariantLight = Color(0xFFC3C9B6)
    override val scrimLight = Color(0xFF000000)
    override val inverseSurfaceLight = Color(0xFF2E312A)
    override val inverseOnSurfaceLight = Color(0xFFF0F2E6)
    override val inversePrimaryLight = Color(0xFFA4D56E)
    override val surfaceDimLight = Color(0xFFD9DBCF)
    override val surfaceBrightLight = Color(0xFFF9FAEE)
    override val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight = Color(0xFFF3F5E9)
    override val surfaceContainerLight = Color(0xFFEDEFE3)
    override val surfaceContainerHighLight = Color(0xFFE7E9DD)
    override val surfaceContainerHighestLight = Color(0xFFE2E4D8)

    override val primaryLightMediumContrast = Color(0xFF213D00)
    override val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    override val primaryContainerLightMediumContrast = Color(0xFF365F00)
    override val onPrimaryContainerLightMediumContrast = Color(0xFFEBFFD0)
    override val secondaryLightMediumContrast = Color(0xFF2A3B17)
    override val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    override val secondaryContainerLightMediumContrast = Color(0xFF60734A)
    override val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val tertiaryLightMediumContrast = Color(0xFF003E31)
    override val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    override val tertiaryContainerLightMediumContrast = Color(0xFF00604D)
    override val onTertiaryContainerLightMediumContrast = Color(0xFFDDFFF2)
    override val errorLightMediumContrast = Color(0xFF740006)
    override val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    override val errorContainerLightMediumContrast = Color(0xFFCD302A)
    override val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val backgroundLightMediumContrast = Color(0xFFF9FAEE)
    override val onBackgroundLightMediumContrast = Color(0xFF1A1D15)
    override val surfaceLightMediumContrast = Color(0xFFF9FAEE)
    override val onSurfaceLightMediumContrast = Color(0xFF0F120B)
    override val surfaceVariantLightMediumContrast = Color(0xFFDFE5D1)
    override val onSurfaceVariantLightMediumContrast = Color(0xFF32382B)
    override val outlineLightMediumContrast = Color(0xFF4F5546)
    override val outlineVariantLightMediumContrast = Color(0xFF696F5F)
    override val scrimLightMediumContrast = Color(0xFF000000)
    override val inverseSurfaceLightMediumContrast = Color(0xFF2E312A)
    override val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F2E6)
    override val inversePrimaryLightMediumContrast = Color(0xFFA4D56E)
    override val surfaceDimLightMediumContrast = Color(0xFFC5C8BC)
    override val surfaceBrightLightMediumContrast = Color(0xFFF9FAEE)
    override val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    override val surfaceContainerLowLightMediumContrast = Color(0xFFF3F5E9)
    override val surfaceContainerLightMediumContrast = Color(0xFFE7E9DD)
    override val surfaceContainerHighLightMediumContrast = Color(0xFFDCDED2)
    override val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D3C7)

    override val primaryLightHighContrast = Color(0xFF1A3200)
    override val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    override val primaryContainerLightHighContrast = Color(0xFF2E5200)
    override val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val secondaryLightHighContrast = Color(0xFF20310E)
    override val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    override val secondaryContainerLightHighContrast = Color(0xFF3D4F29)
    override val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val tertiaryLightHighContrast = Color(0xFF003328)
    override val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    override val tertiaryContainerLightHighContrast = Color(0xFF005443)
    override val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val errorLightHighContrast = Color(0xFF600004)
    override val onErrorLightHighContrast = Color(0xFFFFFFFF)
    override val errorContainerLightHighContrast = Color(0xFF98000B)
    override val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    override val backgroundLightHighContrast = Color(0xFFF9FAEE)
    override val onBackgroundLightHighContrast = Color(0xFF1A1D15)
    override val surfaceLightHighContrast = Color(0xFFF9FAEE)
    override val onSurfaceLightHighContrast = Color(0xFF000000)
    override val surfaceVariantLightHighContrast = Color(0xFFDFE5D1)
    override val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    override val outlineLightHighContrast = Color(0xFF282E21)
    override val outlineVariantLightHighContrast = Color(0xFF454B3D)
    override val scrimLightHighContrast = Color(0xFF000000)
    override val inverseSurfaceLightHighContrast = Color(0xFF2E312A)
    override val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    override val inversePrimaryLightHighContrast = Color(0xFFA4D56E)
    override val surfaceDimLightHighContrast = Color(0xFFB8BAAF)
    override val surfaceBrightLightHighContrast = Color(0xFFF9FAEE)
    override val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    override val surfaceContainerLowLightHighContrast = Color(0xFFF0F2E6)
    override val surfaceContainerLightHighContrast = Color(0xFFE2E4D8)
    override val surfaceContainerHighLightHighContrast = Color(0xFFD3D5CA)
    override val surfaceContainerHighestLightHighContrast = Color(0xFFC5C8BC)

    override val primaryDark = Color(0xFFA4D56E)
    override val onPrimaryDark = Color(0xFF1D3700)
    override val primaryContainerDark = Color(0xFF365F00)
    override val onPrimaryContainerDark = Color(0xFFA7D871)
    override val secondaryDark = Color(0xFFB8CE9D)
    override val onSecondaryDark = Color(0xFF243512)
    override val secondaryContainerDark = Color(0xFF3C4E29)
    override val onSecondaryContainerDark = Color(0xFFAAC090)
    override val tertiaryDark = Color(0xFF89D5BD)
    override val onTertiaryDark = Color(0xFF00382C)
    override val tertiaryContainerDark = Color(0xFF00604D)
    override val onTertiaryContainerDark = Color(0xFF8BD8C0)
    override val errorDark = Color(0xFFFFB4AB)
    override val onErrorDark = Color(0xFF690005)
    override val errorContainerDark = Color(0xFFFF5449)
    override val onErrorContainerDark = Color(0xFF5C0004)
    override val backgroundDark = Color(0xFF11140E)
    override val onBackgroundDark = Color(0xFFE2E4D8)
    override val surfaceDark = Color(0xFF11140E)
    override val onSurfaceDark = Color(0xFFE2E4D8)
    override val surfaceVariantDark = Color(0xFF43493A)
    override val onSurfaceVariantDark = Color(0xFFC3C9B6)
    override val outlineDark = Color(0xFF8D9382)
    override val outlineVariantDark = Color(0xFF43493A)
    override val scrimDark = Color(0xFF000000)
    override val inverseSurfaceDark = Color(0xFFE2E4D8)
    override val inverseOnSurfaceDark = Color(0xFF2E312A)
    override val inversePrimaryDark = Color(0xFF3F690C)
    override val surfaceDimDark = Color(0xFF11140E)
    override val surfaceBrightDark = Color(0xFF373A32)
    override val surfaceContainerLowestDark = Color(0xFF0C0F09)
    override val surfaceContainerLowDark = Color(0xFF1A1D15)
    override val surfaceContainerDark = Color(0xFF1E2119)
    override val surfaceContainerHighDark = Color(0xFF282B23)
    override val surfaceContainerHighestDark = Color(0xFF33362E)

    override val primaryDarkMediumContrast = Color(0xFFB9EC82)
    override val onPrimaryDarkMediumContrast = Color(0xFF162B00)
    override val primaryContainerDarkMediumContrast = Color(0xFF709E3E)
    override val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    override val secondaryDarkMediumContrast = Color(0xFFCEE4B1)
    override val onSecondaryDarkMediumContrast = Color(0xFF1A2A08)
    override val secondaryContainerDarkMediumContrast = Color(0xFF83976B)
    override val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    override val tertiaryDarkMediumContrast = Color(0xFF9EEBD3)
    override val onTertiaryDarkMediumContrast = Color(0xFF002C22)
    override val tertiaryContainerDarkMediumContrast = Color(0xFF529E88)
    override val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    override val errorDarkMediumContrast = Color(0xFFFFD2CC)
    override val onErrorDarkMediumContrast = Color(0xFF540003)
    override val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    override val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    override val backgroundDarkMediumContrast = Color(0xFF11140E)
    override val onBackgroundDarkMediumContrast = Color(0xFFE2E4D8)
    override val surfaceDarkMediumContrast = Color(0xFF11140E)
    override val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    override val surfaceVariantDarkMediumContrast = Color(0xFF43493A)
    override val onSurfaceVariantDarkMediumContrast = Color(0xFFD9DFCB)
    override val outlineDarkMediumContrast = Color(0xFFAEB4A2)
    override val outlineVariantDarkMediumContrast = Color(0xFF8C9381)
    override val scrimDarkMediumContrast = Color(0xFF000000)
    override val inverseSurfaceDarkMediumContrast = Color(0xFFE2E4D8)
    override val inverseOnSurfaceDarkMediumContrast = Color(0xFF282B23)
    override val inversePrimaryDarkMediumContrast = Color(0xFF2D5100)
    override val surfaceDimDarkMediumContrast = Color(0xFF11140E)
    override val surfaceBrightDarkMediumContrast = Color(0xFF43463D)
    override val surfaceContainerLowestDarkMediumContrast = Color(0xFF060804)
    override val surfaceContainerLowDarkMediumContrast = Color(0xFF1C1F17)
    override val surfaceContainerDarkMediumContrast = Color(0xFF262921)
    override val surfaceContainerHighDarkMediumContrast = Color(0xFF31342C)
    override val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3F36)

    override val primaryDarkHighContrast = Color(0xFFCEFF99)
    override val onPrimaryDarkHighContrast = Color(0xFF000000)
    override val primaryContainerDarkHighContrast = Color(0xFFA0D16B)
    override val onPrimaryContainerDarkHighContrast = Color(0xFF050E00)
    override val secondaryDarkHighContrast = Color(0xFFE1F8C4)
    override val onSecondaryDarkHighContrast = Color(0xFF000000)
    override val secondaryContainerDarkHighContrast = Color(0xFFB4CA99)
    override val onSecondaryContainerDarkHighContrast = Color(0xFF050E00)
    override val tertiaryDarkHighContrast = Color(0xFFB4FFE6)
    override val onTertiaryDarkHighContrast = Color(0xFF000000)
    override val tertiaryContainerDarkHighContrast = Color(0xFF85D1B9)
    override val onTertiaryContainerDarkHighContrast = Color(0xFF000E09)
    override val errorDarkHighContrast = Color(0xFFFFECE9)
    override val onErrorDarkHighContrast = Color(0xFF000000)
    override val errorContainerDarkHighContrast = Color(0xFFFFAEA5)
    override val onErrorContainerDarkHighContrast = Color(0xFF220001)
    override val backgroundDarkHighContrast = Color(0xFF11140E)
    override val onBackgroundDarkHighContrast = Color(0xFFE2E4D8)
    override val surfaceDarkHighContrast = Color(0xFF11140E)
    override val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    override val surfaceVariantDarkHighContrast = Color(0xFF43493A)
    override val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    override val outlineDarkHighContrast = Color(0xFFEDF2DF)
    override val outlineVariantDarkHighContrast = Color(0xFFBFC5B2)
    override val scrimDarkHighContrast = Color(0xFF000000)
    override val inverseSurfaceDarkHighContrast = Color(0xFFE2E4D8)
    override val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    override val inversePrimaryDarkHighContrast = Color(0xFF2D5100)
    override val surfaceDimDarkHighContrast = Color(0xFF11140E)
    override val surfaceBrightDarkHighContrast = Color(0xFF4E5148)
    override val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    override val surfaceContainerLowDarkHighContrast = Color(0xFF1E2119)
    override val surfaceContainerDarkHighContrast = Color(0xFF2E312A)
    override val surfaceContainerHighDarkHighContrast = Color(0xFF393C34)
    override val surfaceContainerHighestDarkHighContrast = Color(0xFF45483F)
  }
}
