package com.hologrampacific.flyergoblin.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

class HotPinkTheme(val mode: AppColorTheme.LightMode, val contrast: AppColorTheme.Contrast) :
  AppColorTheme {

  override val colorScheme: ColorScheme
    get() {
      return materialColorTheme.colorScheme(mode, contrast)
    }

  override val goblinColor
    get() = colorScheme.primary

  private val materialColorTheme = InternalMaterialColorTheme()

  private class InternalMaterialColorTheme : MaterialColorTheme {
    override val primaryLight = Color(0xFFA400B1)
    override val onPrimaryLight = Color(0xFFFFFFFF)
    override val primaryContainerLight = Color(0xFFCB14D9)
    override val onPrimaryContainerLight = Color(0xFFFFFFFF)
    override val secondaryLight = Color(0xFF933897)
    override val onSecondaryLight = Color(0xFFFFFFFF)
    override val secondaryContainerLight = Color(0xFFFD97FC)
    override val onSecondaryContainerLight = Color(0xFF7C2281)
    override val tertiaryLight = Color(0xFFBA0057)
    override val onTertiaryLight = Color(0xFFFFFFFF)
    override val tertiaryContainerLight = Color(0xFFE4166F)
    override val onTertiaryContainerLight = Color(0xFFFFFFFF)
    override val errorLight = Color(0xFFBA1A1A)
    override val onErrorLight = Color(0xFFFFFFFF)
    override val errorContainerLight = Color(0xFFFFDAD6)
    override val onErrorContainerLight = Color(0xFF93000A)
    override val backgroundLight = Color(0xFFFFF7FA)
    override val onBackgroundLight = Color(0xFF231822)
    override val surfaceLight = Color(0xFFFFF7FA)
    override val onSurfaceLight = Color(0xFF231822)
    override val surfaceVariantLight = Color(0xFFF5DBF0)
    override val onSurfaceVariantLight = Color(0xFF534151)
    override val outlineLight = Color(0xFF867183)
    override val outlineVariantLight = Color(0xFFD8BFD3)
    override val scrimLight = Color(0xFF000000)
    override val inverseSurfaceLight = Color(0xFF392D37)
    override val inverseOnSurfaceLight = Color(0xFFFFEBF9)
    override val inversePrimaryLight = Color(0xFFFFA9FC)
    override val surfaceDimLight = Color(0xFFE8D4E3)
    override val surfaceBrightLight = Color(0xFFFFF7FA)
    override val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight = Color(0xFFFFEFF9)
    override val surfaceContainerLight = Color(0xFFFDE8F7)
    override val surfaceContainerHighLight = Color(0xFFF7E2F1)
    override val surfaceContainerHighestLight = Color(0xFFF1DDEB)

    override val primaryLightMediumContrast = Color(0xFF63006B)
    override val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    override val primaryContainerLightMediumContrast = Color(0xFFBE00CC)
    override val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val secondaryLightMediumContrast = Color(0xFF63016A)
    override val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    override val secondaryContainerLightMediumContrast = Color(0xFFA448A7)
    override val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val tertiaryLightMediumContrast = Color(0xFF700032)
    override val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    override val tertiaryContainerLightMediumContrast = Color(0xFFD60066)
    override val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val errorLightMediumContrast = Color(0xFF740006)
    override val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    override val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    override val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val backgroundLightMediumContrast = Color(0xFFFFF7FA)
    override val onBackgroundLightMediumContrast = Color(0xFF231822)
    override val surfaceLightMediumContrast = Color(0xFFFFF7FA)
    override val onSurfaceLightMediumContrast = Color(0xFF180E17)
    override val surfaceVariantLightMediumContrast = Color(0xFFF5DBF0)
    override val onSurfaceVariantLightMediumContrast = Color(0xFF423140)
    override val outlineLightMediumContrast = Color(0xFF604D5D)
    override val outlineVariantLightMediumContrast = Color(0xFF7B6778)
    override val scrimLightMediumContrast = Color(0xFF000000)
    override val inverseSurfaceLightMediumContrast = Color(0xFF392D37)
    override val inverseOnSurfaceLightMediumContrast = Color(0xFFFFEBF9)
    override val inversePrimaryLightMediumContrast = Color(0xFFFFA9FC)
    override val surfaceDimLightMediumContrast = Color(0xFFD4C1CF)
    override val surfaceBrightLightMediumContrast = Color(0xFFFFF7FA)
    override val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    override val surfaceContainerLowLightMediumContrast = Color(0xFFFFEFF9)
    override val surfaceContainerLightMediumContrast = Color(0xFFF7E2F1)
    override val surfaceContainerHighLightMediumContrast = Color(0xFFEBD7E6)
    override val surfaceContainerHighestLightMediumContrast = Color(0xFFE0CCDA)

    override val primaryLightHighContrast = Color(0xFF520059)
    override val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    override val primaryContainerLightHighContrast = Color(0xFF82008C)
    override val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val secondaryLightHighContrast = Color(0xFF520059)
    override val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    override val secondaryContainerLightHighContrast = Color(0xFF7A207F)
    override val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val tertiaryLightHighContrast = Color(0xFF5E0029)
    override val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    override val tertiaryContainerLightHighContrast = Color(0xFF940044)
    override val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val errorLightHighContrast = Color(0xFF600004)
    override val onErrorLightHighContrast = Color(0xFFFFFFFF)
    override val errorContainerLightHighContrast = Color(0xFF98000A)
    override val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    override val backgroundLightHighContrast = Color(0xFFFFF7FA)
    override val onBackgroundLightHighContrast = Color(0xFF231822)
    override val surfaceLightHighContrast = Color(0xFFFFF7FA)
    override val onSurfaceLightHighContrast = Color(0xFF000000)
    override val surfaceVariantLightHighContrast = Color(0xFFF5DBF0)
    override val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    override val outlineLightHighContrast = Color(0xFF372736)
    override val outlineVariantLightHighContrast = Color(0xFF564354)
    override val scrimLightHighContrast = Color(0xFF000000)
    override val inverseSurfaceLightHighContrast = Color(0xFF392D37)
    override val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    override val inversePrimaryLightHighContrast = Color(0xFFFFA9FC)
    override val surfaceDimLightHighContrast = Color(0xFFC6B3C1)
    override val surfaceBrightLightHighContrast = Color(0xFFFFF7FA)
    override val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    override val surfaceContainerLowLightHighContrast = Color(0xFFFFEBF9)
    override val surfaceContainerLightHighContrast = Color(0xFFF1DDEB)
    override val surfaceContainerHighLightHighContrast = Color(0xFFE2CFDD)
    override val surfaceContainerHighestLightHighContrast = Color(0xFFD4C1CF)

    override val primaryDark = Color(0xFFFFA9FC)
    override val onPrimaryDark = Color(0xFF590060)
    override val primaryContainerDark = Color(0xFFCB14D9)
    override val onPrimaryContainerDark = Color(0xFFFFFFFF)
    override val secondaryDark = Color(0xFFFFA9FC)
    override val onSecondaryDark = Color(0xFF590060)
    override val secondaryContainerDark = Color(0xFF771D7D)
    override val onSecondaryContainerDark = Color(0xFFF591F5)
    override val tertiaryDark = Color(0xFFFFB1C3)
    override val onTertiaryDark = Color(0xFF66002D)
    override val tertiaryContainerDark = Color(0xFFE4166F)
    override val onTertiaryContainerDark = Color(0xFFFFFFFF)
    override val errorDark = Color(0xFFFFB4AB)
    override val onErrorDark = Color(0xFF690005)
    override val errorContainerDark = Color(0xFF93000A)
    override val onErrorContainerDark = Color(0xFFFFDAD6)
    override val backgroundDark = Color(0xFF1A101A)
    override val onBackgroundDark = Color(0xFFF1DDEB)
    override val surfaceDark = Color(0xFF1A101A)
    override val onSurfaceDark = Color(0xFFF1DDEB)
    override val surfaceVariantDark = Color(0xFF534151)
    override val onSurfaceVariantDark = Color(0xFFD8BFD3)
    override val outlineDark = Color(0xFFA18A9D)
    override val outlineVariantDark = Color(0xFF534151)
    override val scrimDark = Color(0xFF000000)
    override val inverseSurfaceDark = Color(0xFFF1DDEB)
    override val inverseOnSurfaceDark = Color(0xFF392D37)
    override val inversePrimaryDark = Color(0xFFA500B2)
    override val surfaceDimDark = Color(0xFF1A101A)
    override val surfaceBrightDark = Color(0xFF423540)
    override val surfaceContainerLowestDark = Color(0xFF150B14)
    override val surfaceContainerLowDark = Color(0xFF231822)
    override val surfaceContainerDark = Color(0xFF271C26)
    override val surfaceContainerHighDark = Color(0xFF322631)
    override val surfaceContainerHighestDark = Color(0xFF3D313C)

    override val primaryDarkMediumContrast = Color(0xFFFFCDF9)
    override val onPrimaryDarkMediumContrast = Color(0xFF47004D)
    override val primaryContainerDarkMediumContrast = Color(0xFFEB41F7)
    override val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    override val secondaryDarkMediumContrast = Color(0xFFFFCDF9)
    override val onSecondaryDarkMediumContrast = Color(0xFF47004D)
    override val secondaryContainerDarkMediumContrast = Color(0xFFCC6CCD)
    override val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    override val tertiaryDarkMediumContrast = Color(0xFFFFD1DA)
    override val onTertiaryDarkMediumContrast = Color(0xFF520023)
    override val tertiaryContainerDarkMediumContrast = Color(0xFFFF4B8A)
    override val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    override val errorDarkMediumContrast = Color(0xFFFFD2CC)
    override val onErrorDarkMediumContrast = Color(0xFF540003)
    override val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    override val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    override val backgroundDarkMediumContrast = Color(0xFF1A101A)
    override val onBackgroundDarkMediumContrast = Color(0xFFF1DDEB)
    override val surfaceDarkMediumContrast = Color(0xFF1A101A)
    override val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    override val surfaceVariantDarkMediumContrast = Color(0xFF534151)
    override val onSurfaceVariantDarkMediumContrast = Color(0xFFEFD5E9)
    override val outlineDarkMediumContrast = Color(0xFFC3ABBE)
    override val outlineVariantDarkMediumContrast = Color(0xFFA08A9C)
    override val scrimDarkMediumContrast = Color(0xFF000000)
    override val inverseSurfaceDarkMediumContrast = Color(0xFFF1DDEB)
    override val inverseOnSurfaceDarkMediumContrast = Color(0xFF322631)
    override val inversePrimaryDarkMediumContrast = Color(0xFF80008A)
    override val surfaceDimDarkMediumContrast = Color(0xFF1A101A)
    override val surfaceBrightDarkMediumContrast = Color(0xFF4E404C)
    override val surfaceContainerLowestDarkMediumContrast = Color(0xFF0D050D)
    override val surfaceContainerLowDarkMediumContrast = Color(0xFF251A24)
    override val surfaceContainerDarkMediumContrast = Color(0xFF30242F)
    override val surfaceContainerHighDarkMediumContrast = Color(0xFF3B2F3A)
    override val surfaceContainerHighestDarkMediumContrast = Color(0xFF473A45)

    override val primaryDarkHighContrast = Color(0xFFFFEAF9)
    override val onPrimaryDarkHighContrast = Color(0xFF000000)
    override val primaryContainerDarkHighContrast = Color(0xFFFFA2FD)
    override val onPrimaryContainerDarkHighContrast = Color(0xFF1C001F)
    override val secondaryDarkHighContrast = Color(0xFFFFEAF9)
    override val onSecondaryDarkHighContrast = Color(0xFF000000)
    override val secondaryContainerDarkHighContrast = Color(0xFFFFA2FD)
    override val onSecondaryContainerDarkHighContrast = Color(0xFF1C001F)
    override val tertiaryDarkHighContrast = Color(0xFFFFEBEE)
    override val onTertiaryDarkHighContrast = Color(0xFF000000)
    override val tertiaryContainerDarkHighContrast = Color(0xFFFFABBF)
    override val onTertiaryContainerDarkHighContrast = Color(0xFF21000A)
    override val errorDarkHighContrast = Color(0xFFFFECE9)
    override val onErrorDarkHighContrast = Color(0xFF000000)
    override val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    override val onErrorContainerDarkHighContrast = Color(0xFF220001)
    override val backgroundDarkHighContrast = Color(0xFF1A101A)
    override val onBackgroundDarkHighContrast = Color(0xFFF1DDEB)
    override val surfaceDarkHighContrast = Color(0xFF1A101A)
    override val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    override val surfaceVariantDarkHighContrast = Color(0xFF534151)
    override val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    override val outlineDarkHighContrast = Color(0xFFFFEAF9)
    override val outlineVariantDarkHighContrast = Color(0xFFD4BBCF)
    override val scrimDarkHighContrast = Color(0xFF000000)
    override val inverseSurfaceDarkHighContrast = Color(0xFFF1DDEB)
    override val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    override val inversePrimaryDarkHighContrast = Color(0xFF80008A)
    override val surfaceDimDarkHighContrast = Color(0xFF1A101A)
    override val surfaceBrightDarkHighContrast = Color(0xFF5A4C58)
    override val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    override val surfaceContainerLowDarkHighContrast = Color(0xFF271C26)
    override val surfaceContainerDarkHighContrast = Color(0xFF392D37)
    override val surfaceContainerHighDarkHighContrast = Color(0xFF443743)
    override val surfaceContainerHighestDarkHighContrast = Color(0xFF50434E)
  }
}
