package com.hologrampacific.flyergoblin.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

class PinkGreenTheme(val mode: AppColorTheme.LightMode, val contrast: AppColorTheme.Contrast) :
  AppColorTheme {

  override val colorScheme: ColorScheme
    get() {
      return materialColorTheme.colorScheme(mode, contrast)
    }

  override val goblinColor
    get() = colorScheme.primary

  private val materialColorTheme = InternalMaterialColorTheme()

  class InternalMaterialColorTheme : MaterialColorTheme {
    override val primaryLight = Color(0xFF3B693A)
    override val onPrimaryLight = Color(0xFFFFFFFF)
    override val primaryContainerLight = Color(0xFFBCF0B4)
    override val onPrimaryContainerLight = Color(0xFF235024)
    override val secondaryLight = Color(0xFF52634F)
    override val onSecondaryLight = Color(0xFFFFFFFF)
    override val secondaryContainerLight = Color(0xFFD5E8CF)
    override val onSecondaryContainerLight = Color(0xFF3B4B38)
    override val tertiaryLight = Color(0xFF8C4A60)
    override val onTertiaryLight = Color(0xFFFFFFFF)
    override val tertiaryContainerLight = Color(0xFFFFD9E2)
    override val onTertiaryContainerLight = Color(0xFF703348)
    override val errorLight = Color(0xFFBA1A1A)
    override val onErrorLight = Color(0xFFFFFFFF)
    override val errorContainerLight = Color(0xFFFFDAD6)
    override val onErrorContainerLight = Color(0xFF93000A)
    override val backgroundLight = Color(0xFFF7FBF1)
    override val onBackgroundLight = Color(0xFF191D17)
    override val surfaceLight = Color(0xFFF7FBF1)
    override val onSurfaceLight = Color(0xFF191D17)
    override val surfaceVariantLight = Color(0xFFDEE5D8)
    override val onSurfaceVariantLight = Color(0xFF424940)
    override val outlineLight = Color(0xFF72796F)
    override val outlineVariantLight = Color(0xFFC2C9BD)
    override val scrimLight = Color(0xFF000000)
    override val inverseSurfaceLight = Color(0xFF2D322C)
    override val inverseOnSurfaceLight = Color(0xFFEEF2E9)
    override val inversePrimaryLight = Color(0xFFA1D39A)
    override val surfaceDimLight = Color(0xFFD8DBD2)
    override val surfaceBrightLight = Color(0xFFF7FBF1)
    override val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    override val surfaceContainerLowLight = Color(0xFFF1F5EC)
    override val surfaceContainerLight = Color(0xFFECEFE6)
    override val surfaceContainerHighLight = Color(0xFFE6E9E0)
    override val surfaceContainerHighestLight = Color(0xFFE0E4DB)

    override val primaryLightMediumContrast = Color(0xFF113F15)
    override val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    override val primaryContainerLightMediumContrast = Color(0xFF497847)
    override val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val secondaryLightMediumContrast = Color(0xFF2B3A29)
    override val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    override val secondaryContainerLightMediumContrast = Color(0xFF61725D)
    override val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val tertiaryLightMediumContrast = Color(0xFF5B2238)
    override val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    override val tertiaryContainerLightMediumContrast = Color(0xFF9D586F)
    override val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val errorLightMediumContrast = Color(0xFF740006)
    override val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    override val errorContainerLightMediumContrast = Color(0xFFCF2C27)
    override val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    override val backgroundLightMediumContrast = Color(0xFFF7FBF1)
    override val onBackgroundLightMediumContrast = Color(0xFF191D17)
    override val surfaceLightMediumContrast = Color(0xFFF7FBF1)
    override val onSurfaceLightMediumContrast = Color(0xFF0E120D)
    override val surfaceVariantLightMediumContrast = Color(0xFFDEE5D8)
    override val onSurfaceVariantLightMediumContrast = Color(0xFF323830)
    override val outlineLightMediumContrast = Color(0xFF4E544B)
    override val outlineVariantLightMediumContrast = Color(0xFF686F65)
    override val scrimLightMediumContrast = Color(0xFF000000)
    override val inverseSurfaceLightMediumContrast = Color(0xFF2D322C)
    override val inverseOnSurfaceLightMediumContrast = Color(0xFFEEF2E9)
    override val inversePrimaryLightMediumContrast = Color(0xFFA1D39A)
    override val surfaceDimLightMediumContrast = Color(0xFFC4C8BF)
    override val surfaceBrightLightMediumContrast = Color(0xFFF7FBF1)
    override val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    override val surfaceContainerLowLightMediumContrast = Color(0xFFF1F5EC)
    override val surfaceContainerLightMediumContrast = Color(0xFFE6E9E0)
    override val surfaceContainerHighLightMediumContrast = Color(0xFFDADED5)
    override val surfaceContainerHighestLightMediumContrast = Color(0xFFCFD3CA)

    override val primaryLightHighContrast = Color(0xFF04340B)
    override val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    override val primaryContainerLightHighContrast = Color(0xFF265326)
    override val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val secondaryLightHighContrast = Color(0xFF21301F)
    override val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    override val secondaryContainerLightHighContrast = Color(0xFF3D4D3B)
    override val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val tertiaryLightHighContrast = Color(0xFF4F182E)
    override val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    override val tertiaryContainerLightHighContrast = Color(0xFF72354B)
    override val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    override val errorLightHighContrast = Color(0xFF600004)
    override val onErrorLightHighContrast = Color(0xFFFFFFFF)
    override val errorContainerLightHighContrast = Color(0xFF98000A)
    override val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    override val backgroundLightHighContrast = Color(0xFFF7FBF1)
    override val onBackgroundLightHighContrast = Color(0xFF191D17)
    override val surfaceLightHighContrast = Color(0xFFF7FBF1)
    override val onSurfaceLightHighContrast = Color(0xFF000000)
    override val surfaceVariantLightHighContrast = Color(0xFFDEE5D8)
    override val onSurfaceVariantLightHighContrast = Color(0xFF000000)
    override val outlineLightHighContrast = Color(0xFF282E26)
    override val outlineVariantLightHighContrast = Color(0xFF444B42)
    override val scrimLightHighContrast = Color(0xFF000000)
    override val inverseSurfaceLightHighContrast = Color(0xFF2D322C)
    override val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    override val inversePrimaryLightHighContrast = Color(0xFFA1D39A)
    override val surfaceDimLightHighContrast = Color(0xFFB6BAB2)
    override val surfaceBrightLightHighContrast = Color(0xFFF7FBF1)
    override val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    override val surfaceContainerLowLightHighContrast = Color(0xFFEEF2E9)
    override val surfaceContainerLightHighContrast = Color(0xFFE0E4DB)
    override val surfaceContainerHighLightHighContrast = Color(0xFFD2D6CD)
    override val surfaceContainerHighestLightHighContrast = Color(0xFFC4C8BF)

    override val primaryDark = Color(0xFFA1D39A)
    override val onPrimaryDark = Color(0xFF09390F)
    override val primaryContainerDark = Color(0xFF235024)
    override val onPrimaryContainerDark = Color(0xFFBCF0B4)
    override val secondaryDark = Color(0xFFB9CCB3)
    override val onSecondaryDark = Color(0xFF253423)
    override val secondaryContainerDark = Color(0xFF3B4B38)
    override val onSecondaryContainerDark = Color(0xFFD5E8CF)
    override val tertiaryDark = Color(0xFFFFB1C8)
    override val onTertiaryDark = Color(0xFF541D32)
    override val tertiaryContainerDark = Color(0xFF703348)
    override val onTertiaryContainerDark = Color(0xFFFFD9E2)
    override val errorDark = Color(0xFFFFB4AB)
    override val onErrorDark = Color(0xFF690005)
    override val errorContainerDark = Color(0xFF93000A)
    override val onErrorContainerDark = Color(0xFFFFDAD6)
    override val backgroundDark = Color(0xFF10140F)
    override val onBackgroundDark = Color(0xFFE0E4DB)
    override val surfaceDark = Color(0xFF10140F)
    override val onSurfaceDark = Color(0xFFE0E4DB)
    override val surfaceVariantDark = Color(0xFF424940)
    override val onSurfaceVariantDark = Color(0xFFC2C9BD)
    override val outlineDark = Color(0xFF8C9388)
    override val outlineVariantDark = Color(0xFF424940)
    override val scrimDark = Color(0xFF000000)
    override val inverseSurfaceDark = Color(0xFFE0E4DB)
    override val inverseOnSurfaceDark = Color(0xFF2D322C)
    override val inversePrimaryDark = Color(0xFF3B693A)
    override val surfaceDimDark = Color(0xFF10140F)
    override val surfaceBrightDark = Color(0xFF363A34)
    override val surfaceContainerLowestDark = Color(0xFF0B0F0A)
    override val surfaceContainerLowDark = Color(0xFF191D17)
    override val surfaceContainerDark = Color(0xFF1D211B)
    override val surfaceContainerHighDark = Color(0xFF272B25)
    override val surfaceContainerHighestDark = Color(0xFF323630)

    override val primaryDarkMediumContrast = Color(0xFFB6EAAF)
    override val onPrimaryDarkMediumContrast = Color(0xFF002D07)
    override val primaryContainerDarkMediumContrast = Color(0xFF6C9C68)
    override val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    override val secondaryDarkMediumContrast = Color(0xFFCFE2C9)
    override val onSecondaryDarkMediumContrast = Color(0xFF1A2919)
    override val secondaryContainerDarkMediumContrast = Color(0xFF84967F)
    override val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    override val tertiaryDarkMediumContrast = Color(0xFFFFD0DC)
    override val onTertiaryDarkMediumContrast = Color(0xFF471227)
    override val tertiaryContainerDarkMediumContrast = Color(0xFFC67B92)
    override val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    override val errorDarkMediumContrast = Color(0xFFFFD2CC)
    override val onErrorDarkMediumContrast = Color(0xFF540003)
    override val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    override val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    override val backgroundDarkMediumContrast = Color(0xFF10140F)
    override val onBackgroundDarkMediumContrast = Color(0xFFE0E4DB)
    override val surfaceDarkMediumContrast = Color(0xFF10140F)
    override val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
    override val surfaceVariantDarkMediumContrast = Color(0xFF424940)
    override val onSurfaceVariantDarkMediumContrast = Color(0xFFD8DED2)
    override val outlineDarkMediumContrast = Color(0xFFADB4A9)
    override val outlineVariantDarkMediumContrast = Color(0xFF8C9288)
    override val scrimDarkMediumContrast = Color(0xFF000000)
    override val inverseSurfaceDarkMediumContrast = Color(0xFFE0E4DB)
    override val inverseOnSurfaceDarkMediumContrast = Color(0xFF272B25)
    override val inversePrimaryDarkMediumContrast = Color(0xFF245125)
    override val surfaceDimDarkMediumContrast = Color(0xFF10140F)
    override val surfaceBrightDarkMediumContrast = Color(0xFF41463F)
    override val surfaceContainerLowestDarkMediumContrast = Color(0xFF050805)
    override val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1F19)
    override val surfaceContainerDarkMediumContrast = Color(0xFF252923)
    override val surfaceContainerHighDarkMediumContrast = Color(0xFF2F342E)
    override val surfaceContainerHighestDarkMediumContrast = Color(0xFF3B3F39)

    override val primaryDarkHighContrast = Color(0xFFC9FEC1)
    override val onPrimaryDarkHighContrast = Color(0xFF000000)
    override val primaryContainerDarkHighContrast = Color(0xFF9DCF96)
    override val onPrimaryContainerDarkHighContrast = Color(0xFF000F01)
    override val secondaryDarkHighContrast = Color(0xFFE3F5DC)
    override val onSecondaryDarkHighContrast = Color(0xFF000000)
    override val secondaryContainerDarkHighContrast = Color(0xFFB6C8B0)
    override val onSecondaryContainerDarkHighContrast = Color(0xFF030E03)
    override val tertiaryDarkHighContrast = Color(0xFFFFEBEF)
    override val onTertiaryDarkHighContrast = Color(0xFF000000)
    override val tertiaryContainerDarkHighContrast = Color(0xFFFEABC4)
    override val onTertiaryContainerDarkHighContrast = Color(0xFF20000C)
    override val errorDarkHighContrast = Color(0xFFFFECE9)
    override val onErrorDarkHighContrast = Color(0xFF000000)
    override val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
    override val onErrorContainerDarkHighContrast = Color(0xFF220001)
    override val backgroundDarkHighContrast = Color(0xFF10140F)
    override val onBackgroundDarkHighContrast = Color(0xFFE0E4DB)
    override val surfaceDarkHighContrast = Color(0xFF10140F)
    override val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    override val surfaceVariantDarkHighContrast = Color(0xFF424940)
    override val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
    override val outlineDarkHighContrast = Color(0xFFECF2E6)
    override val outlineVariantDarkHighContrast = Color(0xFFBEC5B9)
    override val scrimDarkHighContrast = Color(0xFF000000)
    override val inverseSurfaceDarkHighContrast = Color(0xFFE0E4DB)
    override val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    override val inversePrimaryDarkHighContrast = Color(0xFF245125)
    override val surfaceDimDarkHighContrast = Color(0xFF10140F)
    override val surfaceBrightDarkHighContrast = Color(0xFF4D514B)
    override val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
    override val surfaceContainerLowDarkHighContrast = Color(0xFF1D211B)
    override val surfaceContainerDarkHighContrast = Color(0xFF2D322C)
    override val surfaceContainerHighDarkHighContrast = Color(0xFF383D36)
    override val surfaceContainerHighestDarkHighContrast = Color(0xFF444841)
  }
}
